<?php

/**
 * @file
 * Contains archivesspace.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function archivesspace_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the archivesspace module.
    case 'help.page.archivesspace':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides integration between Drupal and ArchivesSpace') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function archivesspace_theme() {
  return [
    'archivesspace' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_install().
 *
 * Drupal complains about "Mismatched entity and/or field definitions" after
 * installing title_length. We fix it with db_change_varchar_field.
 * See https://www.drupal.org/project/title_length/issues/2950092
 */
function archivesspace_install(){
  db_change_varchar_field('node', 'title', 8000);
}

/**
 * Change length of a varchar entity field with data, safe with entity-updates.
 *
 * This updates the storage schema, the databasse schema, and the last
 * installed schema.
 *
 * The entity schema must also be changed in code in the entities
 * baseFieldDefinitions() or in an alter.
 *
 * @param string $entity_type_id
 *   The entity type.
 * @param string $field_name
 *   The field name to change.
 * @param int $field_length
 *   The new length of the field, must be larger than the previous value.
 */
function db_change_varchar_field($entity_type_id, $field_name, $field_length) {
  // Ignore entity manager caches.
  /** @var \Drupal\Core\Entity\EntityManager $entity_manager */
  $entity_manager = \Drupal::service('entity.manager');
  $entity_manager->useCaches(FALSE);

  /** @var \Drupal\Core\Entity\EntityLastInstalledSchemaRepositoryInterface $schema_repository */
  $schema_repository = \Drupal::service('entity.last_installed_schema.repository');
  /** @var \Drupal\Core\Entity\EntityFieldManager $entity_field_manager */
  $entity_field_manager = \Drupal::service('entity_field.manager');
  $base_field_definitions = $entity_field_manager->getBaseFieldDefinitions($entity_type_id);
  $schema_repository->setLastInstalledFieldStorageDefinition($base_field_definitions[$field_name]);
  $field_storage_definitions = $schema_repository->getLastInstalledFieldStorageDefinitions($entity_type_id);
  $field_storage_definitions[$field_name]['schema'] = $field_storage_definitions[$field_name]->getSchema();
  $field_storage_definitions[$field_name]['schema']['columns']['value']['length'] = $field_length;
  $schema_repository->setLastInstalledFieldStorageDefinitions($entity_type_id, $field_storage_definitions);
  $is_revisionable = $field_storage_definitions[$field_name]->isRevisionable();

  // Update the storage schema.
  $key_value = \Drupal::keyValue('entity.storage_schema.sql');
  $key_name = $entity_type_id . '.field_schema_data.' . $field_name;
  $storage_schema = $key_value->get($key_name);
  $storage_schema[$entity_type_id . '_field_data']['fields'][$field_name]['length'] = $field_length;
  if ($is_revisionable) {
    $storage_schema[$entity_type_id . '_field_revision']['fields'][$field_name]['length'] = $field_length;
  }
  $key_value->set($key_name, $storage_schema);

  // Change node title length (data table).
  $schema = Drupal\Core\Database\Database::getConnection()->schema();
  $schema->changeField($entity_type_id . '_field_data', $field_name, $field_name, [
    'type' => 'varchar',
    'length' => $field_length,
    'binary' => FALSE,
    'not null' => TRUE,
  ]);

  // Change node title length (revisions table).
  $schema = Drupal\Core\Database\Database::getConnection()->schema();
  $schema->changeField($entity_type_id . '_field_revision', $field_name, $field_name, [
    'type' => 'varchar',
    'length' => $field_length,
    'binary' => FALSE,
    'not null' => TRUE,
  ]);
}
