<?php

/**
 * @file
 * Contains archivesspace.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function archivesspace_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the archivesspace module.
    case 'help.page.archivesspace':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides integration between Drupal and ArchivesSpace') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function archivesspace_theme() {
  return [
    'archivesspace' => [
      'render element' => 'children',
    ],
  ];
}
